language:
  - go

sudo: true

go:
  - "1.13.x"

env:
  - GO111MODULE=on

before_install:
  - pip install codecov
  - chmod +x ./scripts/build.sh
  - chmod +x ./scripts/dockerfile.sh

script:
  - ./scripts/build.sh all
  - ./scripts/dockerfile.sh all
  - go test -v ./...

after_success:
  - codecov