runmode: debug
name: user-srv

jwt:
  key: kjf98yr293h67t
  time: 3600

mysql:
  addr: 192.168.0.112:3306
  db: db_cheetah
  user: root
  password: 123456
  maxIdleConns: 10
  maxOpenConns: 100

tracer:
  addr: 127.0.0.1:6831
  context: trace_ctx
  param: req_param