// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

//protoc --proto_path=. --micro_out=. --go_out=. ./api.proto

package micro_srv_auth

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RegisterRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	Age                  int32    `protobuf:"varint,3,opt,name=Age,proto3" json:"Age,omitempty"`
	Addr                 string   `protobuf:"bytes,4,opt,name=Addr,proto3" json:"Addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RegisterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegisterRequest) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *RegisterRequest) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

type RegisterRespond struct {
	Code                 int32    `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Uid                  string   `protobuf:"bytes,2,opt,name=Uid,proto3" json:"Uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRespond) Reset()         { *m = RegisterRespond{} }
func (m *RegisterRespond) String() string { return proto.CompactTextString(m) }
func (*RegisterRespond) ProtoMessage()    {}
func (*RegisterRespond) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *RegisterRespond) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRespond.Unmarshal(m, b)
}
func (m *RegisterRespond) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRespond.Marshal(b, m, deterministic)
}
func (m *RegisterRespond) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRespond.Merge(m, src)
}
func (m *RegisterRespond) XXX_Size() int {
	return xxx_messageInfo_RegisterRespond.Size(m)
}
func (m *RegisterRespond) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRespond.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRespond proto.InternalMessageInfo

func (m *RegisterRespond) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *RegisterRespond) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type LoginRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginRespond struct {
	Code                 int32    `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=Token,proto3" json:"Token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRespond) Reset()         { *m = LoginRespond{} }
func (m *LoginRespond) String() string { return proto.CompactTextString(m) }
func (*LoginRespond) ProtoMessage()    {}
func (*LoginRespond) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *LoginRespond) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRespond.Unmarshal(m, b)
}
func (m *LoginRespond) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRespond.Marshal(b, m, deterministic)
}
func (m *LoginRespond) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRespond.Merge(m, src)
}
func (m *LoginRespond) XXX_Size() int {
	return xxx_messageInfo_LoginRespond.Size(m)
}
func (m *LoginRespond) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRespond.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRespond proto.InternalMessageInfo

func (m *LoginRespond) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *LoginRespond) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type GetRequest struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=Uid,proto3" json:"Uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type GetRespond struct {
	Code                 int32    `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=Username,proto3" json:"Username,omitempty"`
	Age                  int32    `protobuf:"varint,3,opt,name=Age,proto3" json:"Age,omitempty"`
	Addr                 string   `protobuf:"bytes,4,opt,name=Addr,proto3" json:"Addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRespond) Reset()         { *m = GetRespond{} }
func (m *GetRespond) String() string { return proto.CompactTextString(m) }
func (*GetRespond) ProtoMessage()    {}
func (*GetRespond) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{5}
}

func (m *GetRespond) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRespond.Unmarshal(m, b)
}
func (m *GetRespond) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRespond.Marshal(b, m, deterministic)
}
func (m *GetRespond) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRespond.Merge(m, src)
}
func (m *GetRespond) XXX_Size() int {
	return xxx_messageInfo_GetRespond.Size(m)
}
func (m *GetRespond) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRespond.DiscardUnknown(m)
}

var xxx_messageInfo_GetRespond proto.InternalMessageInfo

func (m *GetRespond) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetRespond) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *GetRespond) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *GetRespond) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

type ListRequest struct {
	Page                 int32    `protobuf:"varint,1,opt,name=Page,proto3" json:"Page,omitempty"`
	PageSize             int32    `protobuf:"varint,2,opt,name=PageSize,proto3" json:"PageSize,omitempty"`
	Username             string   `protobuf:"bytes,3,opt,name=Username,proto3" json:"Username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{6}
}

func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

func (m *ListRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type One struct {
	Username             string   `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	Age                  int32    `protobuf:"varint,2,opt,name=Age,proto3" json:"Age,omitempty"`
	Addr                 string   `protobuf:"bytes,3,opt,name=Addr,proto3" json:"Addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *One) Reset()         { *m = One{} }
func (m *One) String() string { return proto.CompactTextString(m) }
func (*One) ProtoMessage()    {}
func (*One) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{7}
}

func (m *One) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_One.Unmarshal(m, b)
}
func (m *One) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_One.Marshal(b, m, deterministic)
}
func (m *One) XXX_Merge(src proto.Message) {
	xxx_messageInfo_One.Merge(m, src)
}
func (m *One) XXX_Size() int {
	return xxx_messageInfo_One.Size(m)
}
func (m *One) XXX_DiscardUnknown() {
	xxx_messageInfo_One.DiscardUnknown(m)
}

var xxx_messageInfo_One proto.InternalMessageInfo

func (m *One) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *One) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *One) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

type ListRespond struct {
	Code                 int32          `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Count                int32          `protobuf:"varint,2,opt,name=Count,proto3" json:"Count,omitempty"`
	All                  map[int32]*One `protobuf:"bytes,3,rep,name=All,proto3" json:"All,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ListRespond) Reset()         { *m = ListRespond{} }
func (m *ListRespond) String() string { return proto.CompactTextString(m) }
func (*ListRespond) ProtoMessage()    {}
func (*ListRespond) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{8}
}

func (m *ListRespond) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRespond.Unmarshal(m, b)
}
func (m *ListRespond) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRespond.Marshal(b, m, deterministic)
}
func (m *ListRespond) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRespond.Merge(m, src)
}
func (m *ListRespond) XXX_Size() int {
	return xxx_messageInfo_ListRespond.Size(m)
}
func (m *ListRespond) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRespond.DiscardUnknown(m)
}

var xxx_messageInfo_ListRespond proto.InternalMessageInfo

func (m *ListRespond) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ListRespond) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *ListRespond) GetAll() map[int32]*One {
	if m != nil {
		return m.All
	}
	return nil
}

type AuthRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthRequest) Reset()         { *m = AuthRequest{} }
func (m *AuthRequest) String() string { return proto.CompactTextString(m) }
func (*AuthRequest) ProtoMessage()    {}
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{9}
}

func (m *AuthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthRequest.Unmarshal(m, b)
}
func (m *AuthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthRequest.Marshal(b, m, deterministic)
}
func (m *AuthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthRequest.Merge(m, src)
}
func (m *AuthRequest) XXX_Size() int {
	return xxx_messageInfo_AuthRequest.Size(m)
}
func (m *AuthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthRequest proto.InternalMessageInfo

func (m *AuthRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type AuthRespond struct {
	Code                 int32    `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Uid                  string   `protobuf:"bytes,2,opt,name=Uid,proto3" json:"Uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthRespond) Reset()         { *m = AuthRespond{} }
func (m *AuthRespond) String() string { return proto.CompactTextString(m) }
func (*AuthRespond) ProtoMessage()    {}
func (*AuthRespond) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{10}
}

func (m *AuthRespond) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthRespond.Unmarshal(m, b)
}
func (m *AuthRespond) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthRespond.Marshal(b, m, deterministic)
}
func (m *AuthRespond) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthRespond.Merge(m, src)
}
func (m *AuthRespond) XXX_Size() int {
	return xxx_messageInfo_AuthRespond.Size(m)
}
func (m *AuthRespond) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthRespond.DiscardUnknown(m)
}

var xxx_messageInfo_AuthRespond proto.InternalMessageInfo

func (m *AuthRespond) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *AuthRespond) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func init() {
	proto.RegisterType((*RegisterRequest)(nil), "micro.srv.auth.RegisterRequest")
	proto.RegisterType((*RegisterRespond)(nil), "micro.srv.auth.RegisterRespond")
	proto.RegisterType((*LoginRequest)(nil), "micro.srv.auth.LoginRequest")
	proto.RegisterType((*LoginRespond)(nil), "micro.srv.auth.LoginRespond")
	proto.RegisterType((*GetRequest)(nil), "micro.srv.auth.GetRequest")
	proto.RegisterType((*GetRespond)(nil), "micro.srv.auth.GetRespond")
	proto.RegisterType((*ListRequest)(nil), "micro.srv.auth.ListRequest")
	proto.RegisterType((*One)(nil), "micro.srv.auth.One")
	proto.RegisterType((*ListRespond)(nil), "micro.srv.auth.ListRespond")
	proto.RegisterMapType((map[int32]*One)(nil), "micro.srv.auth.ListRespond.AllEntry")
	proto.RegisterType((*AuthRequest)(nil), "micro.srv.auth.AuthRequest")
	proto.RegisterType((*AuthRespond)(nil), "micro.srv.auth.AuthRespond")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 469 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x94, 0xc1, 0x6e, 0xd4, 0x30,
	0x10, 0x86, 0x49, 0x9c, 0xa0, 0xed, 0x2c, 0x02, 0x64, 0x38, 0x44, 0x29, 0x82, 0x95, 0xe1, 0xb0,
	0x5c, 0x72, 0xd8, 0x4a, 0x50, 0x71, 0x41, 0xa1, 0x2a, 0x7b, 0xa0, 0xa2, 0x95, 0xa1, 0x07, 0x8e,
	0x29, 0xb1, 0xd2, 0xa8, 0xa9, 0xbd, 0xd8, 0x4e, 0x51, 0x79, 0x36, 0x9e, 0x87, 0xe7, 0x40, 0x8e,
	0xe3, 0x34, 0x9b, 0xed, 0x46, 0xa0, 0xde, 0x66, 0x76, 0xc6, 0xff, 0xff, 0xed, 0x78, 0x1c, 0xd8,
	0xc9, 0x56, 0x65, 0xb2, 0x92, 0x42, 0x0b, 0xfc, 0xf0, 0xb2, 0xfc, 0x2e, 0x45, 0xa2, 0xe4, 0x55,
	0x92, 0xd5, 0xfa, 0x9c, 0x08, 0x78, 0x44, 0x59, 0x51, 0x2a, 0xcd, 0x24, 0x65, 0x3f, 0x6a, 0xa6,
	0x34, 0x8e, 0x61, 0x72, 0xaa, 0x98, 0xe4, 0xd9, 0x25, 0x8b, 0xbc, 0x99, 0x37, 0xdf, 0xa1, 0x5d,
	0x6e, 0x6a, 0x27, 0x99, 0x52, 0x3f, 0x85, 0xcc, 0x23, 0xdf, 0xd6, 0x5c, 0x8e, 0x1f, 0x03, 0x4a,
	0x0b, 0x16, 0xa1, 0x99, 0x37, 0x0f, 0xa9, 0x09, 0x31, 0x86, 0x20, 0xcd, 0x73, 0x19, 0x05, 0x4d,
	0x67, 0x13, 0x93, 0xb7, 0x7d, 0x43, 0xb5, 0x12, 0x3c, 0x37, 0x6d, 0x07, 0x22, 0xb7, 0x66, 0x21,
	0x6d, 0x62, 0x23, 0x76, 0x5a, 0x3a, 0x0f, 0x13, 0x92, 0x8f, 0xf0, 0xe0, 0x48, 0x14, 0x25, 0xbf,
	0x23, 0x26, 0xd9, 0xef, 0x74, 0xb6, 0xbb, 0x3f, 0x85, 0xf0, 0xab, 0xb8, 0x60, 0xbc, 0x3d, 0x6c,
	0x13, 0xf2, 0x1c, 0x60, 0xc9, 0xb4, 0xf3, 0x6f, 0x09, 0xbd, 0x1b, 0xc2, 0xb3, 0xb6, 0xbe, 0x5d,
	0xb7, 0xcf, 0xec, 0x0f, 0x98, 0xff, 0x6d, 0x7c, 0xdf, 0x60, 0x7a, 0x54, 0xaa, 0x0e, 0x02, 0x43,
	0x70, 0x92, 0x15, 0x9d, 0x89, 0x89, 0xed, 0x9f, 0x2f, 0xd8, 0x97, 0xf2, 0x97, 0x35, 0x09, 0x69,
	0x97, 0xaf, 0x01, 0xa0, 0x75, 0x00, 0xb2, 0x04, 0x74, 0xcc, 0xd9, 0xe8, 0x5c, 0x5b, 0x46, 0x7f,
	0x93, 0x11, 0xf5, 0x18, 0x7f, 0x7b, 0x0e, 0x72, 0x74, 0xc2, 0x07, 0xa2, 0xe6, 0xba, 0xd5, 0xb2,
	0x09, 0x7e, 0x03, 0x28, 0xad, 0xaa, 0x08, 0xcd, 0xd0, 0x7c, 0xba, 0x78, 0x95, 0xac, 0xef, 0x6a,
	0xd2, 0xd3, 0x4c, 0xd2, 0xaa, 0x3a, 0xe4, 0x5a, 0x5e, 0x53, 0x73, 0x20, 0xfe, 0x04, 0x13, 0xf7,
	0x83, 0x61, 0xbc, 0x60, 0xd7, 0xad, 0x99, 0x09, 0xf1, 0x6b, 0x08, 0xaf, 0xb2, 0xaa, 0xb6, 0xdc,
	0xd3, 0xc5, 0x93, 0xa1, 0xee, 0x31, 0x67, 0xd4, 0x76, 0xbc, 0xf3, 0xf7, 0x3d, 0xf2, 0x12, 0xa6,
	0x69, 0xad, 0xcf, 0xdd, 0x88, 0xbb, 0x5d, 0xf0, 0xfa, 0xbb, 0xb0, 0xe7, 0x9a, 0xfe, 0x63, 0x85,
	0x17, 0x7f, 0x7c, 0x08, 0xcc, 0x2c, 0xf1, 0x67, 0x98, 0xb8, 0x47, 0x80, 0x5f, 0x0c, 0x71, 0x06,
	0xef, 0x31, 0x1e, 0x69, 0x68, 0xcc, 0xc9, 0x3d, 0x7c, 0x08, 0x61, 0xb3, 0xd3, 0xf8, 0xd9, 0xc6,
	0xcc, 0x7a, 0x4f, 0x26, 0xde, 0x56, 0x75, 0x32, 0xef, 0x01, 0x2d, 0x99, 0xc6, 0xf1, 0xb0, 0xed,
	0x66, 0xeb, 0xe3, 0xdb, 0x6b, 0x4e, 0xe0, 0x03, 0x04, 0xe6, 0x92, 0xf0, 0xee, 0xed, 0x57, 0x67,
	0x25, 0x76, 0x47, 0xee, 0xd5, 0x6a, 0x98, 0xc9, 0x6e, 0x6a, 0xf4, 0x2e, 0x25, 0xde, 0x52, 0x6c,
	0x35, 0xce, 0xee, 0x37, 0x1f, 0xbb, 0xbd, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xb3, 0xc7, 0xd5,
	0xee, 0xf9, 0x04, 0x00, 0x00,
}
